CREATE TABLE ZL_POLICE_LOG
(
SN VARCHAR2(50) NOT NULL,
LOGINNAME VARCHAR2(50),
NAME VARCHAR2(50),
USERID VARCHAR2(50),
IP VARCHAR2(50),
DB VARCHAR2(50),
SFZH VARCHAR2(50),
CJR VARCHAR2(50),
CJSJ TIMESTAMP(6),
XGR VARCHAR2(50),
XGSJ TIMESTAMP(6),
SCR VARCHAR2(50),
SCSJ TIMESTAMP(6),
SCBJ VARCHAR2(2),
JG VARCHAR2(10),
CONTENT CLOB,
LB VARCHAR2(2),
NOT CLUSTER PRIMARY KEY(SN)) STORAGE(ON MAIN, CLUSTERBTR) ;
COMMENT ON TABLE ZL_POLICE_LOG IS '公安接口查询日志';
COMMENT ON COLUMN ZL_POLICE_LOG.CJR IS '创建人';
COMMENT ON COLUMN ZL_POLICE_LOG.CJSJ IS '创建时间';
COMMENT ON COLUMN ZL_POLICE_LOG.DB IS '单位代码';
COMMENT ON COLUMN ZL_POLICE_LOG.IP IS '查询人iP地址';
COMMENT ON COLUMN ZL_POLICE_LOG.JG IS '机构代码';
COMMENT ON COLUMN ZL_POLICE_LOG.LOGINNAME IS '登录名';
COMMENT ON COLUMN ZL_POLICE_LOG.NAME IS '查询人姓名';
COMMENT ON COLUMN ZL_POLICE_LOG.SCBJ IS '删除标记';
COMMENT ON COLUMN ZL_POLICE_LOG.SCR IS '删除人';
COMMENT ON COLUMN ZL_POLICE_LOG.SCSJ IS '删除时间';
COMMENT ON COLUMN ZL_POLICE_LOG.SFZH IS '所查身份证号码';
COMMENT ON COLUMN ZL_POLICE_LOG.SN IS '主键';
COMMENT ON COLUMN ZL_POLICE_LOG.USERID IS '查询人SN';
COMMENT ON COLUMN ZL_POLICE_LOG.XGR IS '修改人';
COMMENT ON COLUMN ZL_POLICE_LOG.XGSJ IS '修改时间';
